name: Fortify Analysis

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '16 0 * * 5'

jobs:
  fortify:
    uses: fortify/.github/.github/workflows/fortify-analysis.yml@main
    secrets: inherit
